### ISSUE TITLE
Value_Counts() continues to throw AttributeError for CategoricalColumn type even after newest merge.

### ISSUE THREAD

**Issue by egoolish** [gpuopenanalytics/pygdf#169]
```
df = pd.DataFrame({'a': ['a', 'a', 'y', 'a', 'b', 'b', 'c', 'd', 'y', 'a', 'c', 'a'], 'b': [1, 2, 9, 0, 1, 6, 1, 3,  6, 3, 7, 6]})
df['a'] = df['a'].astype('category')
gdf = DataFrame.from_pandas(df)
print(gdf['a'].value_counts())
```
throws
```
Traceback (most recent call last):
  File "test3.py", line 12, in <module>
    print(gdf['a'].value_counts())
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+233.g16dead6-py3.6.egg/pygdf/series.py", line 746, in value_counts
    vals, cnts = self._column.value_counts(type=type)
AttributeError: 'CategoricalColumn' object has no attribute 'value_counts'
```
where expected output should be something like
```
a    5
y    2
c    2
b    2
d    1
Name: a, dtype: int64
```

**Comment by kkraus14** [comment]
Just to confirm: you installed pygdf from source with the latest build?

**Comment by dantegd** [comment]
It does not throw that error in my dev machine (the one I pushed from), let me check installing the github master in a new conda env

**Comment by dantegd** [comment]
Example runs fine in my computer with latest `pygdf` and `libgdf` freshly installed: 

```
df = pd.DataFrame({'a': ['a', 'a', 'y', 'a', 'b', 'b', 'c', 'd', 'y', 'a', 'c', 'a'], 'b': [1, 2, 9, 0, 1, 6, 1, 3,  6, 3, 7, 6]})
df['a'] = df['a'].astype('category')
gdf = DataFrame.from_pandas(df)
print(gdf['a'].value_counts())

a    5
b    2
c    2
y    2
d    1

```

**Comment by randerzander** [comment]
@egoolish can you try reproducing the issue with a re-build from PyGDF master?
